import React from 'react';
import type { Metadata } from 'next';
import { OutcomesView } from '@/components/OutcomesView';
import { BreadcrumbSchema, ItemListSchema } from '@/components/StructuredData';
import { constructMetadata } from '@/lib/seo';
import outcomesData from '@/content/outcomes.json';

export const metadata: Metadata = constructMetadata({
  title: 'Outcomes & Deliverables — Transformation Architecture & Decision Matrix',
  description:
    'Key deliverables generated by TNI²TRI 2026: Enterprise Diagnostic Dossier, Readiness Scorecard, Priority Intervention Blueprint, and the 6-way Transformation Decision Matrix.',
  path: '/outcomes',
  keywords: [
    'TNI2TRI Deliverables',
    'Transformation Decision Matrix',
    'Enterprise Diagnostic Dossier',
    'Transformation Readiness Scorecard',
    'Industrial Transformation Outcomes',
  ],
});

export default function OutcomesPage() {
  const deliverableItems = outcomesData.deliverables.map((d) => ({
    name: `${d.title}`,
    description: `${d.subtitle} — ${d.description}`,
  }));

  return (
    <>
      <BreadcrumbSchema
        items={[{ name: 'Outcomes', item: '/outcomes' }]}
      />
      <ItemListSchema
        name="Key Transformation Outcomes & Deliverables"
        description="Formal deliverables and executive governance matrices produced through the diagnostic assessment"
        items={deliverableItems}
      />
      <OutcomesView />
    </>
  );
}
