import { NextRequest, NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export const dynamic = 'force-dynamic';

const RECIPIENTS = ['admin@mjtechsolutions.in', 'mail@tni2tri.org'];

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const {
      regId,
      orgName,
      industrySector,
      location,
      orgType,
      yearsInOperation,
      primaryProducts,
      marketsServed,
      orgSize,
      annualTurnover,
      numLocations,
      contactName,
      contactDesignation,
      contactEmail,
      contactPhone,
      transformationContexts = [],
      primaryQuestion,
    } = body;

    const timestamp = new Date().toISOString();
    const formattedDate = new Date().toLocaleString('en-IN', {
      timeZone: 'Asia/Kolkata',
      dateStyle: 'full',
      timeStyle: 'medium',
    });

    const subject = `[TNI²TRI 2026 Registration] ${orgName || 'New Enterprise'} (${regId || 'Initiation'})`;

    const textContent = `
======================================================
TNI²TRI 2026 ENTERPRISE REGISTRATION TRIGGER NOTIFICATION
======================================================
Registration ID:     ${regId || 'Pending'}
Timestamp:           ${formattedDate} (IST) / ${timestamp}
Notification To:     ${RECIPIENTS.join(', ')}

------------------------------------------------------
1. ORGANISATION IDENTIFICATION & PROFILE
------------------------------------------------------
Organisation Name:   ${orgName || 'N/A'}
Industry Sector:     ${industrySector || 'N/A'}
Organisation Type:   ${orgType || 'N/A'}
Location / Plants:   ${location || 'N/A'}
Years in Operation:  ${yearsInOperation || 'N/A'}
Primary Products:    ${primaryProducts || 'N/A'}
Markets Served:      ${marketsServed || 'N/A'}

------------------------------------------------------
2. OPERATING SCALE & PROFILE
------------------------------------------------------
Approximate Size:    ${orgSize || 'N/A'}
Annual Turnover:     ${annualTurnover || 'N/A'}
Total Facilities:    ${numLocations || 'N/A'}

------------------------------------------------------
3. DESIGNATED EXECUTIVE CONTACT
------------------------------------------------------
Full Name:           ${contactName || 'N/A'}
Designation:         ${contactDesignation || 'N/A'}
Corporate Email:     ${contactEmail || 'N/A'}
Telephone / Mobile:  ${contactPhone || 'N/A'}

------------------------------------------------------
4. TRANSFORMATION FOCUS & INQUIRY
------------------------------------------------------
Transformation Contexts:
${transformationContexts.map((c: string) => ` - ${c}`).join('\n') || 'None specified'}

Primary Strategic Question / Ambition:
${primaryQuestion || 'None provided'}

------------------------------------------------------
Status: Trigger email generated by TNI²TRI 2026 Registration Portal.
======================================================
`;

    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${subject}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #f8fafc; color: #1e293b; padding: 24px; margin: 0; }
    .container { max-width: 640px; margin: 0 auto; background: #ffffff; border-radius: 12px; border: 1px solid #e2e8f0; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05); }
    .header { background-color: #002d62; color: #ffffff; padding: 24px; text-align: left; }
    .header h1 { font-size: 20px; margin: 0 0 6px 0; font-weight: 800; letter-spacing: -0.02em; }
    .header p { font-size: 13px; margin: 0; color: #93c5fd; font-family: monospace; }
    .content { padding: 24px; }
    .badge { display: inline-block; background-color: #eff6ff; color: #1d4ed8; padding: 4px 10px; border-radius: 9999px; font-size: 12px; font-weight: bold; border: 1px solid #bfdbfe; margin-bottom: 16px; }
    .section-title { font-size: 14px; font-weight: 700; color: #002d62; text-transform: uppercase; letter-spacing: 0.05em; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; margin: 20px 0 12px 0; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 12px; font-size: 13px; }
    td { padding: 8px 10px; vertical-align: top; border-bottom: 1px solid #f1f5f9; }
    td.label { width: 38%; color: #64748b; font-weight: 600; }
    td.val { width: 62%; color: #0f172a; font-weight: 500; }
    .highlight-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 14px; font-size: 13px; line-height: 1.6; margin-top: 8px; }
    .footer { background: #f8fafc; border-top: 1px solid #e2e8f0; padding: 16px 24px; font-size: 11px; color: #64748b; text-align: center; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>TNI²TRI 2026 — Enterprise Registration Dossier</h1>
      <p>Registration Identifier: ${regId || 'Pending'} • ${formattedDate}</p>
    </div>
    <div class="content">
      <div class="badge">Automatic Secretariat Trigger Notification</div>
      <p style="font-size: 14px; line-height: 1.5; margin: 0 0 16px 0;">
        A new enterprise registration has been submitted through the <strong>TNI²TRI 2026 Industrial Intelligence Portal</strong>. Details are summarized below for secretariat evaluation and onboarding initiation.
      </p>

      <div class="section-title">1. Organisation Profile</div>
      <table>
        <tr><td class="label">Organisation Name</td><td class="val"><strong>${orgName || 'N/A'}</strong></td></tr>
        <tr><td class="label">Industry Sector</td><td class="val">${industrySector || 'N/A'}</td></tr>
        <tr><td class="label">Organisation Type</td><td class="val">${orgType || 'N/A'}</td></tr>
        <tr><td class="label">Location (Plants/HQ)</td><td class="val">${location || 'N/A'}</td></tr>
        <tr><td class="label">Years in Operation</td><td class="val">${yearsInOperation || 'N/A'}</td></tr>
        <tr><td class="label">Primary Products</td><td class="val">${primaryProducts || 'N/A'}</td></tr>
        <tr><td class="label">Markets Served</td><td class="val">${marketsServed || 'N/A'}</td></tr>
      </table>

      <div class="section-title">2. Operating Scale</div>
      <table>
        <tr><td class="label">Organisation Size</td><td class="val">${orgSize || 'N/A'}</td></tr>
        <tr><td class="label">Annual Turnover</td><td class="val">${annualTurnover || 'N/A'}</td></tr>
        <tr><td class="label">Operating Facilities</td><td class="val">${numLocations || 'N/A'}</td></tr>
      </table>

      <div class="section-title">3. Primary Executive Contact</div>
      <table>
        <tr><td class="label">Designated Contact</td><td class="val"><strong>${contactName || 'N/A'}</strong></td></tr>
        <tr><td class="label">Designation / Role</td><td class="val">${contactDesignation || 'N/A'}</td></tr>
        <tr><td class="label">Corporate Email</td><td class="val"><a href="mailto:${contactEmail}">${contactEmail || 'N/A'}</a></td></tr>
        <tr><td class="label">Contact Telephone</td><td class="val">${contactPhone || 'N/A'}</td></tr>
      </table>

      <div class="section-title">4. Transformation Context & Questions</div>
      <div class="highlight-box">
        <strong>Selected Contexts:</strong>
        <ul style="margin: 6px 0 10px 18px; padding: 0;">
          ${(transformationContexts || []).map((c: string) => `<li>${c}</li>`).join('') || '<li>None specified</li>'}
        </ul>
        <strong>Primary Transformation Question:</strong>
        <p style="margin: 4px 0 0 0; font-style: italic;">"${primaryQuestion || 'None provided'}"</p>
      </div>
    </div>
    <div class="footer">
      This notification was automatically triggered to ${RECIPIENTS.join(' and ')} upon completion of registration on TNI²TRI 2026.
    </div>
  </div>
</body>
</html>
`;

    // Check if SMTP environment variables are set
    const smtpHost = process.env.SMTP_HOST;
    const smtpUser = process.env.SMTP_USER;
    const smtpPass = process.env.SMTP_PASS;
    const smtpPort = parseInt(process.env.SMTP_PORT || '587', 10);
    const smtpSecure = process.env.SMTP_SECURE === 'true' || smtpPort === 465;
    const smtpFrom = process.env.SMTP_FROM || `"TNI²TRI 2026 Portal" <noreply@tni2tri.org>`;

    let emailSent = false;
    let dispatchMethod = 'simulated';

    if (smtpHost && smtpUser && smtpPass) {
      try {
        const transporter = nodemailer.createTransport({
          host: smtpHost,
          port: smtpPort,
          secure: smtpSecure,
          auth: {
            user: smtpUser,
            pass: smtpPass,
          },
        });

        await transporter.sendMail({
          from: smtpFrom,
          to: RECIPIENTS,
          replyTo: contactEmail || undefined,
          subject,
          text: textContent,
          html: htmlContent,
        });

        emailSent = true;
        dispatchMethod = 'smtp';
        console.log(`[TNI²TRI Email] Successfully dispatched email via SMTP to ${RECIPIENTS.join(', ')}`);
      } catch (smtpErr) {
        console.error('[TNI²TRI Email] SMTP sending failed:', smtpErr);
      }
    } else {
      console.log(`[TNI²TRI Email Trigger] Email prepared for recipients: ${RECIPIENTS.join(', ')}`);
      console.log(`[TNI²TRI Email Trigger] Subject: ${subject}`);
      console.log(`[TNI²TRI Email Trigger] Note: SMTP_HOST/USER/PASS not configured. Payload logged.`);
      emailSent = true;
      dispatchMethod = 'logged';
    }

    return NextResponse.json({
      success: true,
      message: 'Registration dossier registered and trigger email processed',
      regId,
      recipients: RECIPIENTS,
      emailSent,
      dispatchMethod,
    });
  } catch (error: any) {
    console.error('[TNI²TRI Email API Error]', error);
    return NextResponse.json(
      {
        success: false,
        error: error?.message || 'Failed to process registration email trigger',
      },
      { status: 500 }
    );
  }
}
